= Contributing to Eclipse JNoSQL
:toc: auto

Thanks for your interest in this project.

== Project description

* https://projects.eclipse.org/projects/technology.jnosql

== Developer resources

Information regarding source code management, builds, coding standards, and
more.

* https://projects.eclipse.org/projects/technology.jnosql/developer

The project maintains the following source code repositories


* https://github.com/eclipse/jnosql
* https://github.com/eclipse/jnosql-databases
* https://github.com/eclipse/jnosql-extension


== Eclipse Contributor Agreement

Before your contribution can be accepted by the project team contributors must
electronically sign the Eclipse Contributor Agreement (ECA).

* http://www.eclipse.org/legal/ECA.php

Commits that are provided by non-committers must have a Signed-off-by field in
the footer indicating that the author is aware of the terms by which the
contribution has been provided to the project. The non-committer must
additionally have an Eclipse Foundation account and must have a signed Eclipse
Contributor Agreement (ECA) on file.

For more information, please see the Eclipse Committer Handbook:
https://www.eclipse.org/projects/handbook/#resources-commit


=== Developer Certificate of Origin - DCO

This is a security layer for the project and for the developers. It is mandatory.

Follow one of these two methods to add DCO to your commits:

==== 1. Command line

Follow the steps:
**Step 1:** Configure your local git environment adding the same name and e-mail configured at your GitHub account. It helps to sign commits manually during reviews and suggestions.

[source, Bash]
----
git config --global user.name “Name”
git config --global user.email “email@domain.com.br”
----

**Step 2:** Add the Signed-off-by line with the `'-s'` flag in the git commit command:

[source, Bash]
----
$ git commit -s -m "This is my commit message"
----

==== 2. GitHub website

You can also manually sign your commits during GitHub reviews and suggestions, follow the steps below:

**Step 1:** When the commit changes box opens, manually type or paste your signature in the comment box, see the example:

[source, Bash]
----
Signed-off-by: Name < e-mail address >
----

== Contact

Contact the project developers via the project's "dev" list.

* https://dev.eclipse.org/mailman/listinfo/jnosql-dev


== Issues

If you found a bug or have an idea, check out the following sections before submitting your contribution.

=== Check the issue tracker

All our issues are centralized in our https://github.com/eclipse/jnosql[**main repository**], it is quite likely that you will find a topic that is being discussed. Check the https://github.com/eclipse/jnosql/issues[**open issues**], another good way to start is https://github.com/eclipse/jnosql/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22[**good first issues**].

=== Open an issue for any new problem

Writing a good issue will help our team better analyze and manage your contributions, therefore, follow the standards and best practices below:

**With the title:**

**Project:Scope - Title Description**

- **Project:** Name of the project or repository you want to contribute to.

- **Scope:** Add what your issue refers to:

- **https://github.com/eclipse/jnosql/issues/new?assignees=&labels=bug&template=bug_report.md&title=[Bug report]:** Report a reproducible bug.

- **https://github.com/eclipse/jnosql/issues/new?assignees=&labels=&template=feature_request.md&title=[Feature request]:** Suggest a new idea for Eclipse JNoSQL.

> **Example: Eclipse JNoSQL:feat request - Suggestion for a better user experience**

**With the issue description:**

Try to explain the scenario to us by following these tips:

- **Context:** explain the conditions which led you to write this issue.
- **Problem or idea:** the context should lead to something, an idea or a problem that you’re facing.
- **Solution or next step:** this where you move forward. You can engage others (request feedback), assign somebody else to the issue, or simply leave it for further investigation, but you absolutely need to propose a next step towards solving the issue.